# Generated by Django 5.2 on 2026-06-07 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='contacto_principal',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='ticket',
            name='contacto_secundario',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='correo_cliente',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='detalle_reclamo',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='ticket',
            name='id_cliente',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='numero_contrato',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='tipo_interaccion',
            field=models.CharField(choices=[('reclamo', 'Reclamo'), ('consulta', 'Consulta')], default='reclamo', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='cliente',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='titulo',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
